---
title: "ajustes_codigos_pos_oficina"
output: html_notebook
date: "`r Sys.Date()`"
---
#PARA ENTREGA DENTRO DO PRAZO DO ADITIVO
#Ajustes no relatorio Markdown (Lu Fusinatto)

1.~~Separar um tutoriral de carregamento de dados e transformação para o distance à parte do fluxo de análise. 
Adaptar para facilitar inclusão de novos conjuntos de dados, inclusive do SMART.~~ **FEITO** (por hora, mas preciso conseguir preencher os valores `NA`'s na coluna speed...)


2. No tutorial de fluxo de análise, incluir uma opção incial com a alternativa de trabalhar com o conjunto de dados do pacote ou com outro conjunto de dados. 
**OBS**: incluir no tutorial de fluxo de análise o que está no arquivo `carregamento_novos_dados.Rmd`.

3. O html não gerou outputs para o fluxo estratificado (gerar um novo html após correções e disponibilizar); 

4. Incluir o fluxo de análise: dados estratificados + covariável de tamanho de grupo.



# Ajustes nos dados/códigos (Vitor)

1.~~Criar uma opção para carregamento dos dados do SMART~~ **FEITO**

2.~~Corrigir nome da família Tinamidae;~~

3. ~~Corrigir o esforço amostral para incluir trilhas percorridas sem registros dos animais.
Sugestão do Ricardo: calcular o esforço amostral total para cada UC antes de filtrar por espécie. Usar esse esforço amostral como base quando estiver analisando os dados de cada espécie. Filtrar por UC/ano/estacao. Generalizar para todas as espécies;~~

4. ~~Incluir um filtro por gênero;~~

5. ~~Adicionar colunas genero, familia e ordem;~~

6. ~~Incluir opção de filtro pelo código cnuc;~~ 

7. Verificar nomes dos modelos nas tabelas de output das estimativas de taxa de encontro, abundancia e densidade. Todas devem ter a coluna modelo (com o nome) e a coluna formula.

8. Verificar título do eixo dos gráficos (probabilidade de detecação)

9. Incluir intervalo de confiança:
- Tabela da taxa de encontro/abundancia
- Grafico da serie temporal abundancia/densidade

10. Padronizar limites do eixo y nos gráficos das séries temporais;

11. Combinações de gráficos de abundância e densidade /UC/ano, /estação amostral/UC/ano

12. Para gerar a tabela de densidade, incluir um argumento que possibilite apresentar os resultados tanto por hectare quanto por Km quadrado;

13. Para a legenda das tabelas de abundancia/densidade. Pensar em como ajustar as legendas de abundância/densidade (p. ex. ind/area). Para dados não corrigidos pelo tamnho do grupo a contagem será de ocorrências, que podem ser tanto indivíduos quanto grupos. Para casos de dados corrigidos pelo tamanho do grupo, estimativas serão de número de indivíduos.

14. Completar os arquivos help;

15. Ajeitar os boxplots interativos

*EXTRAS**

~~. incluir variável velocidade~~

#PARA PENSAR FUTURAMENTE - COM BASE NOS APONTAMENTOS DA OFICINA
#Ajustes nas análises/estratégias analíticas
1. Pesquisar/entender Distância efetiva de avistamento.
2. Pacote Unmarked
  - exponencial negativa
  - estratégia para lidar com repetições
  - estratégia para lidar com pico em zero.
  - série temporal anual (? anotei mais não lembro muito bem do que se tratava)
  
#Pensar estratégias de disponbilizar os dados ao público - maior alcance
-Olhar Darwin Core e dados ecológicos 

- Dryad? DataOne? Algum outro banco de dados?

**OBS**: (Formato Darwin Core é específico para dados de ocorrência. O PPBio tá tentando se adequar a esse formato, mas encontrando dificuldade pq perde muito dado, não será o formato único de tombamento. Provavelmente ficará no DataOne também, bom pra dados ecológicos).

# Novas atualizações necessárias

- incluir mensagens de erro alertando quando o nome da uc, ou nome de familia, genero ou sp estiverem errados (por enquanto gera resultado mesmo com nomes errados, inserir warning)